
1.
CREATE TABLE DEPT
(
DEPTNO NUMBER(5) PRIMARY KEY NOT NULL,
DNAME VARCHAR(100),
LOC VARCHAR(100),
CONSTRAINT dname_dept CHECK (DNAME         IN('ACCOUNTING','RESEARCH','SALES','OPERATIONS'))
)
2.
INSERT INTO DEPT VALUES (10,'ACCOUNTING','NEW-YORK');
INSERT INTO DEPT VALUES (20,'RESEARCH','DALLAS');
INSERT INTO DEPT VALUES (30,'SALES','CHICAGO');
INSERT INTO DEPT VALUES (40,'OPERATIONS','BOSTON');
3.
CREATE TABLE EMP AS SELECT * FROM SCOTT.EMP;
4.
INSERT INTO EMP VALUES(7369,'Bidon',NULL,NULL,NULL,NULL,NULL,NULL);
5.
ROLLBACK;
6.
ALTER TABLE EMP ADD CONSTRAINT emp_pk PRIMARY KEY(EMPNO);
ALTER TABLE EMP ADD CONSTRAINT emp_fk FOREIGN KEY (DEPTNO) REFERENCES DEPT(DEPTNO);
ALTER TABLE EMP ADD CONSTRAINT emp_mg FOREIGN KEY(MGR) REFERENCES EMP(EMPNO);
7.
INSERT INTO EMP VALUES(7369, 'WILSON', 'MANAGER', 7839, '17-NOV-91', 3500.00, 600.00, 10);
INSERT INTO EMP VALUES(7657, 'WILSON','MANAGER', 7839, '17-NOV-91', 3500.00, 600.00, 50);
INSERT INTO EMP VALUES(7657, 'WILSON', 'MANAGER', 7000,'17-NOV-91', 3500.00, 600.00, 10);
INSERT INTO EMP VALUES(7657, 'WILSON', 'MANAGER', 7839, '17-NOV-91', 3500.00,600.00, 10);
8.COMMIT ;
Mise à jour de la base de données

****************************************************************

1.
UPDATE DEPT SET LOC='PITTSBURGH' WHERE DNAME='SALES';

2.
UPDATE EMP SET SAL=SAL*1.1 WHERE COMM> Sal*0.5;

3.
UPDATE EMP
SET COMM=(SELECT AVG(COMM) FROM EMP) 
WHERE HIREDATE<'01-JAN-82' AND COMM IS NULL;

4.
ROLLBACK;

5.
DELETE FROM DEPT WHERE DEPTNO=20;

***************************************************************
1.
SELECT ename, sal, comm, sal+comm 
FROM EMP
WHERE job='SALESMAN';

2.
SELECT ename
FROM EMP
ORDER BY COMM/SAL DESC;

3.
SELECT ename
FROM EMP
WHERE COMM<SAL*0.25;

4.
SELECT COUNT(ENAME)
FROM EMP
WHERE DEPTNO=10;

5.
SELECT COUNT(ename) 
FROM EMP
WHERE COMM IS NOT NULL;

6.
SELECT  COUNT(DISTINCT JOB)
FROM EMP;

7.
SELECT JOB, AVG(SAL)
FROM EMP
GROUP BY JOB;

8.
SELECT SUM(SAL)
FROM EMP
WHERE DEPTNO=30;

9.
SELECT e.ENAME, d.DNAME
FROM EMP e, DEPT d
WHERE e.DEPTNO=d.DEPTNO;

10.
SELECT ENAME, JOB, SAL
FROM EMP
WHERE SAL= (SELECT MAX(SAL) FROM EMP);

11.
SELECT ENAME
FROM EMP
WHERE SAL>(SELECT SAL FROM EMP WHERE ENAME='JONES');

12.
SELECT ENAME
FROM EMP
WHERE JOB =(SELECT JOB FROM EMP WHERE ENAME='JONES')
AND ENAME <> 'JONES';
13.

SELECT ENAME
FROM EMP
WHERE MGR=(SELECT MGR FROM EMP WHERE ENAME='CLARCK')
AND ENAME <>'CLARCK';

14.
SELECT ENAME,JOB
FROM EMP
WHERE (JOB,MGR) IN (SELECT JOB,MGR FROM EMP WHERE ENAME='TURNER')
AND ENAME <>'CLARCK';

15.
SELECT ENAME,JOB
FROM EMP
WHERE HIREDATE < ALL(SELECT HIREDATE FROM EMP WHERE DEPTNO=10);

16.
SELECT mgr.ENAME,e.ENAME
FROM EMP e, EMP mgr
WHERE mgr.MGR=e.EMPNO;

17.
SELECT e.ENAME
FROM EMP e, EMP mgr
WHERE mgr.MGR=e.EMPNO AND mgr.DEPTNO<>e.DEPTNO;
