
CREATE TABLE PIECE
(
    NOP NUMBER(5) ,
    DESIGNATION VARCHAR(50),
    COULEUR VARCHAR(50),
    POIDS NUMBER(10)
)
CREATE TABLE SERVICE
(
    NOS NUMBER(5),
    INTITULE VARCHAR(50),
    LOCALISATION VARCHAR(50)
)
CREATE TABLE ORDRE
(
    NOP NUMBER(5),
    NOS NUMBER(5),
    QUANTITE NUMBER(10)
)
CREATE TABLE NOMENCLATURE
(
    NOPA NUMBER(5),
    NOPC NUMBER(5),
    QUANTITE NUMBER(10)
)

*************************************************************************

1.
INSERT INTO PIECE VALUES(1,’PIECE1’,’NOIR’,80);
INSERT INTO PIECE VALUES(1,’PIECE2’,’BLEU’,90);
INSERT INTO PIECE VALUES(1,’PIECE3’,’JAUNE’,60);
2.
INSERT INTO SERVICE VALUES(2,'S1','CASABLANCA');
INSERT INTO SERVICE VALUES(2,'S2','ESSAOUIRA');
INSERT INTO SERVICE VALUES(2,'S3','SAFI');
3.
INSERT INTO ORDRE VALUES(1,3,115);
INSERT INTO ORDRE VALUES(1,4,96);
INSERT INTO ORDRE VALUES(1,5,231);
4.
INSERT INTO NOMENCLATURE VALUES(9,3,10);
INSERT INTO NOMENCLATURE VALUES(4,2,10);
INSERT INTO NOMENCLATURE VALUES(7,2,11);
5.
ALTER TABLE PIECE 
ADD CONSTRAINT pc_pk PRIMARY KEY(NOP);
ALTER TABLE SERVICE 
ADD CONSTRAINT sv_pk PRIMARY KEY(NOS);
ALTER TABLE ORDRE
ADD CONSTRAINT ORDRE_CLP PRIMARY KEY (NOP, NOS) ;
ALTER TABLE ORDRE 
ADD CONSTRAINT o_fk1 FOREIGN KEY (NOP) REFERENCES PIECE(NOP);
ALTER TABLE ORDRE
ADD CONSTRAINT o_fk2 FOREIGN KEY (NOS) REFERENCES SERVICE(NOS);
ALTER TABLE NOMENCLATURE
ADD CONSTRAINT NOM_CLP PRIMARY KEY (NOPA, NOPC) ;
ALTER TABLE NOMENCLATURE 
ADD CONSTRAINT n_fk1 FOREIGN KEY (NOPA) REFERENCES PIECE(NOP);
ALTER TABLE NOMENCLATURE 
ADD CONSTRAINT n_fk2 FOREIGN KEY (NOPC) REFERENCES PIECE(NOP);
6.
7.
ALTER TABLE PIECE
ADD CONSTRAINT color CHECK (COULEUR IN('ROUGE','VERTE','BLEUE','JAUNE'));

*************************************************************************

1.
ALTER TABLE PIECE MODIFY(DESIGNATION VARCHAR(60));
ALTER TABLE SERVICE MODIFY(INTITULE VARCHAR(60));
2.
ALTER TABLE SERVICE MODIFY (LOCALISATION VARCHAR(40)) ;
3.
ALTER TABLE SERVICE ADD (DIRECTEUR VARCHAR(20)) ;
4.
ALTER TABLE SERVICE DROP UNIQUE (LOCALISATION) ;
5.
ALTER TABLE PIECE DROP PRIMARY KEY;
6.
ALTER TABLE PIECE DROP CONSTRAINT color;
7.
DROP TABLE NOMENCLATURE;
8.
 DROP TABLE ORDRE CASCADE CONSTRAINTS ;
SELECT * FROM PIECE ;
SELECT * FROM SERVICE ;

